[package]
name = "viron"
version = "2.0.0"
authors = ["Vir Team <dev@virgori.org>"]
description = "Viron standalone toolchain and package manager for Vir"
license = "Apache-2.0"

[toolchain]
vir = "2026.1"

[modules]
root = "viron"
entry = "src/main.vri"
