/*
 * ptx_gen.c – Q-IR → PTX Assembly Text Emitter
 * ===============================================
 * Lowers Q-IR arithmetic, memory, compare, bitwise, SIMD and control-flow
 * ops into NVIDIA PTX assembly that can be JIT-compiled via CUDA Driver API.
 *
 * PTX target: .version 7.0, sm_70+ (Volta+), .address_size 64.
 *
 * Register convention:
 *   %rd<N>  – 64-bit integer (maps from Q-IR virtual regs)
 *   %r<N>   – 32-bit integer (temporaries, indices)
 *   %f<N>   – 32-bit float
 *   %fd<N>  – 64-bit float
 *   %p<N>   – predicate
 */

#include "ptx_gen.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

/* ═══════════════════════════════════════════════════════
 * Text Buffer Management
 * ═══════════════════════════════════════════════════════ */

void ptx_buf_init(ptx_buf_t *pb) {
    pb->data = malloc(PTX_BUF_INIT);
    pb->len  = 0;
    pb->cap  = PTX_BUF_INIT;
    pb->data[0] = '\0';
    pb->next_pred  = 0;
    pb->next_r32   = 0;
    pb->next_r64   = 0;
    pb->next_f32   = 0;
    pb->next_f64   = 0;
    pb->next_label = 0;
}

void ptx_buf_free(ptx_buf_t *pb) {
    free(pb->data);
    pb->data = NULL;
    pb->len = pb->cap = 0;
}

static void ptx_buf_ensure(ptx_buf_t *pb, size_t extra) {
    while (pb->len + extra + 1 > pb->cap) {
        pb->cap *= 2;
        pb->data = realloc(pb->data, pb->cap);
    }
}

static void ptx_emit(ptx_buf_t *pb, const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    /* Measure needed length */
    va_list ap2;
    va_copy(ap2, ap);
    int need = vsnprintf(NULL, 0, fmt, ap2);
    va_end(ap2);

    ptx_buf_ensure(pb, (size_t)need + 1);
    pb->len += vsnprintf(pb->data + pb->len, pb->cap - pb->len, fmt, ap);
    va_end(ap);
}

static void ptx_line(ptx_buf_t *pb, const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    va_list ap2;
    va_copy(ap2, ap);
    int need = vsnprintf(NULL, 0, fmt, ap2);
    va_end(ap2);

    ptx_buf_ensure(pb, (size_t)need + 2);
    pb->len += vsnprintf(pb->data + pb->len, pb->cap - pb->len, fmt, ap);
    va_end(ap);
    pb->data[pb->len++] = '\n';
    pb->data[pb->len] = '\0';
}

/* ═══════════════════════════════════════════════════════
 * Register & Label Allocation
 * ═══════════════════════════════════════════════════════ */

int ptx_alloc_reg(ptx_buf_t *pb, ptx_reg_type_t type) {
    switch (type) {
    case PTX_REG_PRED: return pb->next_pred++;
    case PTX_REG_B16:  return pb->next_r32++;   /* reuse r32 counter */
    case PTX_REG_B32:  return pb->next_r32++;
    case PTX_REG_B64:  return pb->next_r64++;
    case PTX_REG_F32:  return pb->next_f32++;
    case PTX_REG_F64:  return pb->next_f64++;
    }
    return -1;
}

int ptx_alloc_label(ptx_buf_t *pb) {
    return pb->next_label++;
}

/* ═══════════════════════════════════════════════════════
 * Virtual register → PTX register mapping
 * Q-IR vreg N → %rd<N> (64-bit)
 * ═══════════════════════════════════════════════════════ */

static const char *vreg(int n) {
    static char buf[8][32];
    static int idx = 0;
    idx = (idx + 1) & 7;
    snprintf(buf[idx], sizeof(buf[idx]), "%%rd%d", n);
    return buf[idx];
}

static const char *r32(int n) {
    static char buf[4][32];
    static int idx = 0;
    idx = (idx + 1) & 3;
    snprintf(buf[idx], sizeof(buf[idx]), "%%r%d", n);
    return buf[idx];
}

static const char *pred(int n) {
    static char buf[4][32];
    static int idx = 0;
    idx = (idx + 1) & 3;
    snprintf(buf[idx], sizeof(buf[idx]), "%%p%d", n);
    return buf[idx];
}

/* ═══════════════════════════════════════════════════════
 * Preamble & Kernel Structure
 * ═══════════════════════════════════════════════════════ */

void ptx_emit_preamble(ptx_buf_t *pb, int target_sm) {
    ptx_line(pb, "// Generated by Vir PTX emitter");
    ptx_line(pb, ".version 7.0");
    ptx_line(pb, ".target sm_%d", target_sm);
    ptx_line(pb, ".address_size 64");
    ptx_line(pb, "");
}

void ptx_emit_kernel_begin(ptx_buf_t *pb, const ptx_kernel_desc_t *desc) {
    ptx_emit(pb, ".visible .entry %s(\n", desc->name);
    for (int i = 0; i < desc->num_params; i++) {
        ptx_emit(pb, "    .param .u%d param%d%s\n",
                 desc->param_sizes[i] * 8,
                 i,
                 (i < desc->num_params - 1) ? "," : "");
    }
    ptx_line(pb, ")");
    ptx_line(pb, "{");
}

void ptx_emit_reg_decls(ptx_buf_t *pb) {
    if (pb->next_pred > 0)
        ptx_line(pb, "    .reg .pred %%p<%d>;", pb->next_pred);
    if (pb->next_r32 > 0)
        ptx_line(pb, "    .reg .b32 %%r<%d>;", pb->next_r32);
    if (pb->next_r64 > 0)
        ptx_line(pb, "    .reg .b64 %%rd<%d>;", pb->next_r64);
    if (pb->next_f32 > 0)
        ptx_line(pb, "    .reg .f32 %%f<%d>;", pb->next_f32);
    if (pb->next_f64 > 0)
        ptx_line(pb, "    .reg .f64 %%fd<%d>;", pb->next_f64);
    ptx_line(pb, "");
}

void ptx_emit_kernel_end(ptx_buf_t *pb) {
    ptx_line(pb, "    ret;");
    ptx_line(pb, "}");
}

/* ═══════════════════════════════════════════════════════
 * Thread Index Helpers
 * ═══════════════════════════════════════════════════════ */

int ptx_emit_thread_index(ptx_buf_t *pb, const char *dim) {
    /* tid = blockIdx.<dim> * blockDim.<dim> + threadIdx.<dim> */
    int bid  = ptx_alloc_reg(pb, PTX_REG_B32);
    int bdim = ptx_alloc_reg(pb, PTX_REG_B32);
    int tidx = ptx_alloc_reg(pb, PTX_REG_B32);
    int tmp  = ptx_alloc_reg(pb, PTX_REG_B32);
    int tid  = ptx_alloc_reg(pb, PTX_REG_B32);

    ptx_line(pb, "    mov.u32 %s, %%ctaid.%s;", r32(bid), dim);
    ptx_line(pb, "    mov.u32 %s, %%ntid.%s;",  r32(bdim), dim);
    ptx_line(pb, "    mov.u32 %s, %%tid.%s;",   r32(tidx), dim);
    ptx_line(pb, "    mad.lo.u32 %s, %s, %s, %s;",
             r32(tid), r32(bid), r32(bdim), r32(tidx));

    return tid;
}

int ptx_emit_bounds_check(ptx_buf_t *pb, int tid_reg, int n_reg,
                          int exit_label) {
    int p = ptx_alloc_reg(pb, PTX_REG_PRED);
    ptx_line(pb, "    setp.ge.u32 %s, %s, %s;",
             pred(p), r32(tid_reg), r32(n_reg));
    ptx_line(pb, "    @%s bra L_exit_%d;", pred(p), exit_label);
    return p;
}

/* ═══════════════════════════════════════════════════════
 * Operand helpers
 * ═══════════════════════════════════════════════════════ */

static int ensure_in_r64(ptx_buf_t *pb, const q_operand_t *op) {
    switch (op->type) {
    case OPERAND_VREG:
        return (int)op->vreg;
    case OPERAND_IMM: {
        int r = ptx_alloc_reg(pb, PTX_REG_B64);
        ptx_line(pb, "    mov.s64 %s, %lld;", vreg(r), (long long)op->imm);
        return r;
    }
    default:
        return -1;
    }
}

/* ═══════════════════════════════════════════════════════
 * Q-IR → PTX Instruction Lowering
 * ═══════════════════════════════════════════════════════ */

int ptx_lower_block(ptx_buf_t *pb, const q_instruction_t *instrs,
                    int count, const ptx_kernel_desc_t *desc) {
    (void)desc;

    /* Track maximum vreg for reg decl pass */
    for (int i = 0; i < count; i++) {
        const q_instruction_t *ins = &instrs[i];

        /* Update register counters */
        if (ins->dest.type == OPERAND_VREG && (int)ins->dest.vreg >= pb->next_r64)
            pb->next_r64 = (int)ins->dest.vreg + 1;
        if (ins->src1.type == OPERAND_VREG && (int)ins->src1.vreg >= pb->next_r64)
            pb->next_r64 = (int)ins->src1.vreg + 1;
        if (ins->src2.type == OPERAND_VREG && (int)ins->src2.vreg >= pb->next_r64)
            pb->next_r64 = (int)ins->src2.vreg + 1;
    }

    /* Emit instructions */
    for (int i = 0; i < count; i++) {
        const q_instruction_t *ins = &instrs[i];
        int d, s1, s2;

        switch (ins->opcode) {

        /* ── Labels ── */
        case Q_LABEL:
            ptx_line(pb, "L_%u:", ins->dest.label);
            break;

        case Q_NOP:
            /* no-op: omit */
            break;

        /* ── Data movement ── */
        case Q_MOVE:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            ptx_line(pb, "    mov.s64 %s, %s;", vreg(d), vreg(s1));
            break;

        case Q_LOAD:
            d = (int)ins->dest.vreg;
            if (ins->src1.type == OPERAND_IMM) {
                ptx_line(pb, "    mov.s64 %s, %lld;",
                         vreg(d), (long long)ins->src1.imm);
            } else {
                s1 = ensure_in_r64(pb, &ins->src1);
                ptx_line(pb, "    ld.global.s64 %s, [%s];", vreg(d), vreg(s1));
            }
            break;

        case Q_STORE:
            d  = ensure_in_r64(pb, &ins->dest);
            s1 = ensure_in_r64(pb, &ins->src1);
            ptx_line(pb, "    st.global.s64 [%s], %s;", vreg(d), vreg(s1));
            break;

        case Q_LOAD_WORD: {
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            int tmp = ptx_alloc_reg(pb, PTX_REG_B64);
            ptx_line(pb, "    shl.b64 %s, %s, 3;", vreg(tmp), vreg(s2));
            ptx_line(pb, "    add.s64 %s, %s, %s;", vreg(tmp), vreg(s1), vreg(tmp));
            ptx_line(pb, "    ld.global.s64 %s, [%s];", vreg(d), vreg(tmp));
            break;
        }

        case Q_STORE_WORD: {
            d  = ensure_in_r64(pb, &ins->dest);
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            int tmp = ptx_alloc_reg(pb, PTX_REG_B64);
            ptx_line(pb, "    shl.b64 %s, %s, 3;", vreg(tmp), vreg(s2));
            ptx_line(pb, "    add.s64 %s, %s, %s;", vreg(tmp), vreg(s1), vreg(tmp));
            ptx_line(pb, "    st.global.s64 [%s], %s;", vreg(tmp), vreg(d));
            break;
        }

        /* ── Arithmetic ── */
        case Q_ADD:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    add.s64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_SUB:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    sub.s64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_MUL:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    mul.lo.s64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_DIV:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    div.s64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_MOD:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    rem.s64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        /* ── Bitwise ── */
        case Q_AND:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    and.b64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_OR:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    or.b64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_XOR:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    xor.b64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_SHL:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    shl.b64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_SHR:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    shr.s64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        /* ── Comparisons ── */
        case Q_CMP_EQ: case Q_CMP_GT: case Q_CMP_LT:
        case Q_CMP_GE: case Q_CMP_LE: {
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            int p = ptx_alloc_reg(pb, PTX_REG_PRED);

            const char *cmp_op = "eq";
            switch (ins->opcode) {
            case Q_CMP_EQ: cmp_op = "eq"; break;
            case Q_CMP_GT: cmp_op = "gt"; break;
            case Q_CMP_LT: cmp_op = "lt"; break;
            case Q_CMP_GE: cmp_op = "ge"; break;
            case Q_CMP_LE: cmp_op = "le"; break;
            default: break;
            }
            ptx_line(pb, "    setp.%s.s64 %s, %s, %s;",
                     cmp_op, pred(p), vreg(s1), vreg(s2));
            /* selp: dest = p ? 1 : 0 */
            ptx_line(pb, "    selp.s64 %s, 1, 0, %s;", vreg(d), pred(p));
            break;
        }

        /* ── Control flow ── */
        case Q_JUMP:
            if (ins->dest.type == OPERAND_LABEL)
                ptx_line(pb, "    bra L_%u;", ins->dest.label);
            break;

        case Q_JUMP_IF:
            s1 = ensure_in_r64(pb, &ins->src1);
            {
                int p = ptx_alloc_reg(pb, PTX_REG_PRED);
                ptx_line(pb, "    setp.ne.s64 %s, %s, 0;", pred(p), vreg(s1));
                if (ins->dest.type == OPERAND_LABEL)
                    ptx_line(pb, "    @%s bra L_%u;", pred(p), ins->dest.label);
            }
            break;

        case Q_JUMP_IF_NOT:
            s1 = ensure_in_r64(pb, &ins->src1);
            {
                int p = ptx_alloc_reg(pb, PTX_REG_PRED);
                ptx_line(pb, "    setp.eq.s64 %s, %s, 0;", pred(p), vreg(s1));
                if (ins->dest.type == OPERAND_LABEL)
                    ptx_line(pb, "    @%s bra L_%u;", pred(p), ins->dest.label);
            }
            break;

        case Q_RET:
            ptx_line(pb, "    ret;");
            break;

        /* ── SIMD / vector (mapped to PTX vector ops) ── */
        case Q_VADD:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            /* Using .f32 vector pairs — 2x f32 in 64-bit */
            ptx_line(pb, "    // VADD: vectorized add");
            ptx_line(pb, "    add.s64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_VSUB:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    sub.s64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_VMUL:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    mul.lo.s64 %s, %s, %s;", vreg(d), vreg(s1), vreg(s2));
            break;

        case Q_VFMA:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            s2 = ensure_in_r64(pb, &ins->src2);
            ptx_line(pb, "    mad.lo.s64 %s, %s, %s, %s;",
                     vreg(d), vreg(s1), vreg(s2), vreg(d));
            break;

        case Q_VLOAD:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            ptx_line(pb, "    ld.global.s64 %s, [%s];", vreg(d), vreg(s1));
            break;

        case Q_VSTORE:
            d  = ensure_in_r64(pb, &ins->dest);
            s1 = ensure_in_r64(pb, &ins->src1);
            ptx_line(pb, "    st.global.s64 [%s], %s;", vreg(d), vreg(s1));
            break;

        case Q_VSPLAT:
            d  = (int)ins->dest.vreg;
            s1 = ensure_in_r64(pb, &ins->src1);
            ptx_line(pb, "    mov.s64 %s, %s;  // broadcast", vreg(d), vreg(s1));
            break;

        /* ── Unsupported on GPU (emit as comment) ── */
        case Q_CALL: case Q_CALL_FUNC:
            ptx_line(pb, "    // UNSUPPORTED: Q_CALL on GPU (device function needed)");
            break;

        case Q_PRINT: case Q_PRINT_STR: case Q_INPUT:
            ptx_line(pb, "    // UNSUPPORTED: I/O on GPU");
            break;

        case Q_ALLOC: case Q_FREE:
            ptx_line(pb, "    // UNSUPPORTED: dynamic alloc on GPU");
            break;

        case Q_TASK_SPAWN: case Q_TASK_YIELD: case Q_TASK_WAIT:
            ptx_line(pb, "    // UNSUPPORTED: tasks on GPU (use streams)");
            break;

        case Q_HALT:
            ptx_line(pb, "    ret; // HALT");
            break;

        default:
            ptx_line(pb, "    // UNHANDLED opcode 0x%02X", ins->opcode);
            break;
        }
    }
    return 0;
}

/* ═══════════════════════════════════════════════════════
 * Convenience: Full kernel generation
 * ═══════════════════════════════════════════════════════ */

char *ptx_generate_kernel(const q_instruction_t *instrs, int count,
                          const ptx_kernel_desc_t *desc) {
    if (!instrs || count <= 0 || !desc || !desc->name) return NULL;

    ptx_buf_t pb;
    ptx_buf_init(&pb);

    int target_sm = desc->target_sm > 0 ? desc->target_sm : 70;

    /* Phase 1: emit body into a temp buffer to discover register usage */
    ptx_buf_t body;
    ptx_buf_init(&body);
    ptx_lower_block(&body, instrs, count, desc);

    /* Phase 2: emit complete PTX with correct register decls */
    ptx_emit_preamble(&pb, target_sm);
    ptx_emit_kernel_begin(&pb, desc);

    /* Copy register counts from body pass */
    pb.next_pred = body.next_pred;
    pb.next_r32  = body.next_r32;
    pb.next_r64  = body.next_r64;
    pb.next_f32  = body.next_f32;
    pb.next_f64  = body.next_f64;

    ptx_emit_reg_decls(&pb);

    /* Load params into registers */
    for (int i = 0; i < desc->num_params; i++) {
        ptx_line(&pb, "    ld.param.u64 %%rd%d, [param%d];", i, i);
    }
    ptx_line(&pb, "");

    /* Append the body */
    ptx_buf_ensure(&pb, body.len);
    memcpy(pb.data + pb.len, body.data, body.len);
    pb.len += body.len;
    pb.data[pb.len] = '\0';

    ptx_emit_kernel_end(&pb);
    ptx_buf_free(&body);

    /* Return the PTX as a malloc'd string */
    char *result = pb.data;
    /* Don't free — caller owns it */
    return result;
}
