"""
codegen_x86.py – x86_64 Code Generation Backend
=================================================
Phase 3 – H3: x86_64 assembly output from Q-IR.

Generates AT&T syntax x86_64 assembly (System V ABI).

Optimizations:
  - Linear-scan register allocator for hot VRegs
  - CMP + Jcc fusion (eliminates SET+TEST intermediary)
  - Peephole: eliminate redundant MOV, fold imm into ADD
  - Stack alignment to 16 bytes

Calling convention: System V AMD64 ABI
  - Args: rdi, rsi, rdx, rcx, r8, r9
  - Callee-saved: rbx, r12-r15  (saved/restored by prologue/epilogue)
  - Return: rax
  - Stack: 16-byte aligned before call
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field
from typing import Optional

from src.ir.instructions.q_ir import (
    Opcode, QInstruction, QFunction, QModule, VReg, Immediate, Label,
)


# System V AMD64 ABI registers
_ARG_REGS = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"]
_CALLEE_SAVED = ["rbx", "r12", "r13", "r14", "r15"]
# Allocatable registers (not rax/rcx/rdx which are used as scratch)
_ALLOC_REGS = ["rbx", "r12", "r13", "r14", "r15", "r8", "r9", "r10", "r11"]


@dataclass
class X86CodegenStats:
    functions_emitted: int = 0
    instructions_emitted: int = 0
    stack_slots_used: int = 0


class X86_64Codegen:
    """Generate x86_64 assembly from Q-IR module."""

    def __init__(self) -> None:
        self.lines: list[str] = []
        self.stats = X86CodegenStats()
        self._string_table: list[str] = []
        # Register allocator state (per-function)
        self._reg_map: dict[str, str] = {}     # VReg.name → physical reg
        self._spill_map: dict[str, int] = {}   # VReg.name → stack offset
        self._spill_count: int = 0
        self._used_callee_saved: set[str] = set()

    def generate(self, module: QModule) -> str:
        """Generate complete x86_64 assembly."""
        self.lines = []
        self._emit_header()
        self._emit_data_section(module)
        self._emit_text_section(module)
        return "\n".join(self.lines)

    def _emit(self, line: str) -> None:
        self.lines.append(line)
        if not line.startswith(".") and not line.startswith("#") and not line.endswith(":"):
            self.stats.instructions_emitted += 1

    def _emit_header(self) -> None:
        self._emit("# Generated by Vir x86_64 backend (Phase 4 — RegAlloc)")
        self._emit("# System V AMD64 ABI")
        self._emit("")

    def _emit_data_section(self, module: QModule) -> None:
        self._emit(".data")
        for i, s in enumerate(module.strings):
            escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            self._emit(f'_str_{i}: .asciz "{escaped}"')
        self._emit("")
        self._emit('_fmt_int: .asciz "%ld\\n"')
        self._emit('_fmt_str: .asciz "%s\\n"')
        self._emit('_fmt_float: .asciz "%f\\n"')
        self._emit("")

    def _emit_text_section(self, module: QModule) -> None:
        self._emit(".text")
        has_main = any(f.name == "main" for f in module.functions)
        if has_main:
            self._emit(".globl _main")
        for func in module.functions:
            self._emit(f".globl _vir_{func.name}")
        self._emit("")

        for func in module.functions:
            self._emit_function(func)

        if has_main:
            self._emit("_main:")
            self._emit("    pushq %rbp")
            self._emit("    movq %rsp, %rbp")
            self._emit("    callq _vir_main")
            self._emit("    xorl %eax, %eax")
            self._emit("    popq %rbp")
            self._emit("    retq")
            self._emit("")

    # ═══════════════════════════════════════════════════
    # Register Allocator (linear scan, frequency-based)
    # ═══════════════════════════════════════════════════

    def _allocate_registers(self, func: QFunction) -> None:
        """Assign physical registers to the most-used VRegs, spill the rest."""
        self._reg_map = {}
        self._spill_map = {}
        self._spill_count = 0
        self._used_callee_saved = set()

        # Count VReg usage frequency
        freq: Counter[str] = Counter()
        all_vregs: set[str] = set()
        for instr in func.body:
            for op in (instr.dest, instr.src1, instr.src2):
                if isinstance(op, VReg):
                    freq[op.name] += 1
                    all_vregs.add(op.name)
        for p in func.params:
            freq[p.name] += 2  # boost params

        # Determine which regs are available (exclude arg regs used by params)
        param_arg_regs = set()
        for i, p in enumerate(func.params):
            if i < len(_ARG_REGS):
                param_arg_regs.add(_ARG_REGS[i])

        # Has any CALL? If so, don't allocate caller-saved regs to loop VRegs
        has_call = any(i.opcode == Opcode.Q_CALL for i in func.body)

        available = []
        for r in _ALLOC_REGS:
            if r in param_arg_regs:
                continue
            if has_call and r in ("r8", "r9", "r10", "r11"):
                continue  # caller-saved, would be clobbered by calls
            available.append(r)

        # Assign registers to most-frequent VRegs
        sorted_vregs = sorted(all_vregs, key=lambda v: freq[v], reverse=True)
        reg_idx = 0
        for vname in sorted_vregs:
            if reg_idx < len(available):
                reg = available[reg_idx]
                self._reg_map[vname] = reg
                if reg in _CALLEE_SAVED:
                    self._used_callee_saved.add(reg)
                reg_idx += 1
            else:
                # Spill to stack
                self._spill_count += 1
                self._spill_map[vname] = -(self._spill_count * 8)

    def _vreg_asm(self, vreg: VReg) -> str:
        """Get assembly operand for a VReg — either register or stack slot."""
        if vreg.name in self._reg_map:
            return f"%{self._reg_map[vreg.name]}"
        offset = self._spill_map.get(vreg.name, -8)
        return f"{offset}(%rbp)"

    def _is_reg(self, vreg: VReg) -> bool:
        """Check if VReg is allocated to a physical register."""
        return vreg.name in self._reg_map

    def _operand_to_asm(self, op) -> str:
        if isinstance(op, Immediate):
            return f"${int(op.value)}"
        if isinstance(op, VReg):
            return self._vreg_asm(op)
        if isinstance(op, Label):
            return f"_vir_{op.name}"
        return str(op)

    # ═══════════════════════════════════════════════════
    # Function Emission
    # ═══════════════════════════════════════════════════

    def _emit_function(self, func: QFunction) -> None:
        label = f"_vir_{func.name}"
        self.stats.functions_emitted += 1

        # Run register allocator
        self._allocate_registers(func)

        # Prologue
        self._emit(f"{label}:")
        self._emit("    pushq %rbp")
        self._emit("    movq %rsp, %rbp")

        # Save callee-saved registers we're using
        saved = sorted(self._used_callee_saved)
        for reg in saved:
            self._emit(f"    pushq %{reg}")

        # Stack space for spills (align to 16)
        spill_bytes = self._spill_count * 8
        # Account for pushes: rbp + len(saved) pushes already done
        total_pushes = 1 + len(saved)  # rbp + callee-saved
        if spill_bytes > 0:
            # Align: (total_pushes * 8 + spill_bytes) must be 16-aligned
            aligned = (spill_bytes + 15) & ~15
            self._emit(f"    subq ${aligned}, %rsp")
            self.stats.stack_slots_used += self._spill_count

        # Load params into their allocated locations
        for i, param in enumerate(func.params):
            if i < len(_ARG_REGS):
                arg_reg = _ARG_REGS[i]
                if self._is_reg(param):
                    dest_reg = self._reg_map[param.name]
                    if dest_reg != arg_reg:
                        self._emit(f"    movq %{arg_reg}, %{dest_reg}")
                else:
                    offset = self._spill_map[param.name]
                    self._emit(f"    movq %{arg_reg}, {offset}(%rbp)")

        # Body — with CMP+Jcc fusion
        body = func.body
        i = 0
        while i < len(body):
            instr = body[i]
            # Peephole: fuse CMP + JUMP_IF
            if (instr.opcode in (Opcode.Q_CMP_LT, Opcode.Q_CMP_GT, Opcode.Q_CMP_GE,
                                  Opcode.Q_CMP_LE, Opcode.Q_CMP_EQ, Opcode.Q_CMP_NE)
                    and i + 1 < len(body)
                    and body[i + 1].opcode == Opcode.Q_JUMP_IF
                    and isinstance(body[i + 1].src1, VReg)
                    and isinstance(instr.dest, VReg)
                    and body[i + 1].src1.name == instr.dest.name):
                self._emit_fused_cmp_jmp(instr, body[i + 1])
                i += 2
                continue
            self._emit_instruction(instr)
            i += 1

        # Epilogue (if no explicit ret)
        if not body or body[-1].opcode != Opcode.Q_RET:
            self._emit_epilogue(saved, spill_bytes)
        self._emit("")

    def _emit_epilogue(self, saved: list[str], spill_bytes: int) -> None:
        if spill_bytes > 0:
            aligned = (spill_bytes + 15) & ~15
            self._emit(f"    addq ${aligned}, %rsp")
        for reg in reversed(saved):
            self._emit(f"    popq %{reg}")
        self._emit("    popq %rbp")
        self._emit("    retq")

    # ═══════════════════════════════════════════════════
    # Instruction Emission
    # ═══════════════════════════════════════════════════

    def _emit_instruction(self, instr: QInstruction) -> None:
        match instr.opcode:
            case Opcode.Q_LOAD:
                self._emit_load(instr)
            case Opcode.Q_MOVE:
                self._emit_move(instr)
            case Opcode.Q_ADD:
                self._emit_binop(instr, "addq")
            case Opcode.Q_SUB:
                self._emit_binop(instr, "subq")
            case Opcode.Q_MUL:
                self._emit_mul(instr)
            case Opcode.Q_DIV:
                self._emit_div(instr)
            case Opcode.Q_MOD:
                self._emit_mod(instr)
            case Opcode.Q_CMP_EQ | Opcode.Q_CMP_NE | Opcode.Q_CMP_GT | Opcode.Q_CMP_LT | Opcode.Q_CMP_GE | Opcode.Q_CMP_LE:
                self._emit_cmp(instr)
            case Opcode.Q_JUMP:
                self._emit_jump(instr)
            case Opcode.Q_JUMP_IF:
                self._emit_jump_if(instr, negate=False)
            case Opcode.Q_JUMP_IF_NOT:
                self._emit_jump_if(instr, negate=True)
            case Opcode.Q_LABEL:
                self._emit_label(instr)
            case Opcode.Q_CALL:
                self._emit_call(instr)
            case Opcode.Q_RET:
                self._emit_ret(instr)
            case Opcode.Q_PRINT:
                self._emit_print(instr)
            case _:
                self._emit(f"    # unhandled: {instr.opcode.name}")

    def _emit_load(self, instr: QInstruction) -> None:
        dest = instr.dest
        src = instr.src1
        if isinstance(src, Immediate):
            val = int(src.value)
            if self._is_reg(dest):
                if val == 0:
                    r = self._reg_map[dest.name]
                    # xor is shorter/faster for zero
                    if r in ("rax", "rbx", "rcx", "rdx", "rsi", "rdi"):
                        r32 = r.replace("r", "e", 1)
                        self._emit(f"    xorl %{r32}, %{r32}")
                    else:
                        self._emit(f"    xorq %{r}, %{r}")
                else:
                    self._emit(f"    movq ${val}, %{self._reg_map[dest.name]}")
            else:
                self._emit(f"    movq ${val}, %rax")
                self._emit(f"    movq %rax, {self._vreg_asm(dest)}")
        elif isinstance(src, VReg):
            self._emit_move_inner(dest, src)

    def _emit_move(self, instr: QInstruction) -> None:
        self._emit_move_inner(instr.dest, instr.src1)

    def _emit_move_inner(self, dest: VReg, src) -> None:
        """Emit a move from src to dest, using registers when possible."""
        if isinstance(src, VReg) and self._is_reg(src) and self._is_reg(dest):
            sr = self._reg_map[src.name]
            dr = self._reg_map[dest.name]
            if sr != dr:
                self._emit(f"    movq %{sr}, %{dr}")
            # else: same register, no-op
        elif isinstance(src, VReg) and self._is_reg(src):
            self._emit(f"    movq %{self._reg_map[src.name]}, {self._vreg_asm(dest)}")
        elif isinstance(src, VReg) and self._is_reg(dest):
            self._emit(f"    movq {self._vreg_asm(src)}, %{self._reg_map[dest.name]}")
        elif isinstance(src, Immediate):
            if self._is_reg(dest):
                self._emit(f"    movq ${int(src.value)}, %{self._reg_map[dest.name]}")
            else:
                self._emit(f"    movq ${int(src.value)}, %rax")
                self._emit(f"    movq %rax, {self._vreg_asm(dest)}")
        else:
            self._emit(f"    movq {self._operand_to_asm(src)}, %rax")
            self._emit(f"    movq %rax, {self._vreg_asm(dest)}")

    def _emit_binop(self, instr: QInstruction, op: str) -> None:
        dest, a, b = instr.dest, instr.src1, instr.src2
        da = self._is_reg(a) if isinstance(a, VReg) else False
        db = self._is_reg(b) if isinstance(b, VReg) else False
        dd = self._is_reg(dest) if isinstance(dest, VReg) else False

        # Best case: dest == a, both in registers
        if (dd and da and isinstance(a, VReg) and isinstance(dest, VReg)
                and self._reg_map.get(dest.name) == self._reg_map.get(a.name)):
            dr = self._reg_map[dest.name]
            if isinstance(b, Immediate):
                val = int(b.value)
                if val == 1 and op == "addq":
                    self._emit(f"    incq %{dr}")
                    return
                self._emit(f"    {op} ${val}, %{dr}")
            elif db:
                self._emit(f"    {op} %{self._reg_map[b.name]}, %{dr}")
            else:
                self._emit(f"    {op} {self._operand_to_asm(b)}, %{dr}")
            return

        # General case: load a into rax, op b, store to dest
        if da and isinstance(a, VReg):
            ra = self._reg_map[a.name]
            if dd and self._reg_map[dest.name] != ra:
                # move a into dest, then op b onto dest
                dr = self._reg_map[dest.name]
                self._emit(f"    movq %{ra}, %{dr}")
                if isinstance(b, Immediate):
                    val = int(b.value)
                    if val == 1 and op == "addq":
                        self._emit(f"    incq %{dr}")
                        return
                    self._emit(f"    {op} ${val}, %{dr}")
                elif db:
                    self._emit(f"    {op} %{self._reg_map[b.name]}, %{dr}")
                else:
                    self._emit(f"    {op} {self._operand_to_asm(b)}, %{dr}")
                return
            # Fallthrough: use rax
            self._emit(f"    movq %{ra}, %rax")
        else:
            self._emit(f"    movq {self._operand_to_asm(a)}, %rax")

        if isinstance(b, Immediate):
            val = int(b.value)
            if val == 1 and op == "addq":
                self._emit("    incq %rax")
            else:
                self._emit(f"    {op} ${val}, %rax")
        elif db:
            self._emit(f"    {op} %{self._reg_map[b.name]}, %rax")
        else:
            self._emit(f"    {op} {self._operand_to_asm(b)}, %rax")

        if dd:
            self._emit(f"    movq %rax, %{self._reg_map[dest.name]}")
        else:
            self._emit(f"    movq %rax, {self._vreg_asm(dest)}")

    def _emit_mul(self, instr: QInstruction) -> None:
        dest, a, b = instr.dest, instr.src1, instr.src2
        self._emit(f"    movq {self._operand_to_asm(a)}, %rax")
        self._emit(f"    imulq {self._operand_to_asm(b)}, %rax")
        if self._is_reg(dest):
            self._emit(f"    movq %rax, %{self._reg_map[dest.name]}")
        else:
            self._emit(f"    movq %rax, {self._vreg_asm(dest)}")

    def _emit_div(self, instr: QInstruction) -> None:
        dest, a, b = instr.dest, instr.src1, instr.src2
        # Save rdx if it's allocated
        rdx_save = None
        for vn, reg in self._reg_map.items():
            if reg == "rdx":
                rdx_save = vn
                break

        self._emit(f"    movq {self._operand_to_asm(a)}, %rax")
        self._emit("    cqto")
        # idivq can't take immediate, must use register
        if isinstance(b, Immediate):
            self._emit(f"    movq ${int(b.value)}, %rcx")
            self._emit("    idivq %rcx")
        elif self._is_reg(b):
            br = self._reg_map[b.name]
            if br == "rdx":
                # rdx will be clobbered by cqto, so load b first
                self._emit(f"    movq %{br}, %rcx")
                self._emit("    idivq %rcx")
            else:
                self._emit(f"    idivq %{br}")
        else:
            self._emit(f"    movq {self._vreg_asm(b)}, %rcx")
            self._emit("    idivq %rcx")

        if self._is_reg(dest):
            self._emit(f"    movq %rax, %{self._reg_map[dest.name]}")
        else:
            self._emit(f"    movq %rax, {self._vreg_asm(dest)}")

    def _emit_mod(self, instr: QInstruction) -> None:
        dest, a, b = instr.dest, instr.src1, instr.src2
        self._emit(f"    movq {self._operand_to_asm(a)}, %rax")
        self._emit("    cqto")
        if isinstance(b, Immediate):
            self._emit(f"    movq ${int(b.value)}, %rcx")
            self._emit("    idivq %rcx")
        elif self._is_reg(b):
            br = self._reg_map[b.name]
            if br == "rdx":
                self._emit(f"    movq %{br}, %rcx")
                self._emit("    idivq %rcx")
            else:
                self._emit(f"    idivq %{br}")
        else:
            self._emit(f"    movq {self._vreg_asm(b)}, %rcx")
            self._emit("    idivq %rcx")
        # Remainder in rdx
        if self._is_reg(dest):
            self._emit(f"    movq %rdx, %{self._reg_map[dest.name]}")
        else:
            self._emit(f"    movq %rdx, {self._vreg_asm(dest)}")

    def _emit_cmp(self, instr: QInstruction) -> None:
        """Standalone CMP (not fused). Materializes 0/1 into dest."""
        dest, a, b = instr.dest, instr.src1, instr.src2
        self._emit(f"    movq {self._operand_to_asm(a)}, %rax")
        self._emit(f"    cmpq {self._operand_to_asm(b)}, %rax")
        set_instr = {
            Opcode.Q_CMP_EQ: "sete", Opcode.Q_CMP_NE: "setne",
            Opcode.Q_CMP_GT: "setg", Opcode.Q_CMP_LT: "setl",
            Opcode.Q_CMP_GE: "setge", Opcode.Q_CMP_LE: "setle",
        }.get(instr.opcode, "sete")
        self._emit(f"    {set_instr} %al")
        self._emit("    movzbq %al, %rax")
        if self._is_reg(dest):
            self._emit(f"    movq %rax, %{self._reg_map[dest.name]}")
        else:
            self._emit(f"    movq %rax, {self._vreg_asm(dest)}")

    def _emit_fused_cmp_jmp(self, cmp_instr: QInstruction, jmp_instr: QInstruction) -> None:
        """Fuse CMP + JUMP_IF into CMP + Jcc (eliminates SET+TEST)."""
        a, b = cmp_instr.src1, cmp_instr.src2
        target = jmp_instr.dest  # Label

        # Emit CMP
        if self._is_reg(a) and isinstance(b, Immediate):
            self._emit(f"    cmpq ${int(b.value)}, %{self._reg_map[a.name]}")
        elif self._is_reg(a) and isinstance(b, VReg) and self._is_reg(b):
            self._emit(f"    cmpq %{self._reg_map[b.name]}, %{self._reg_map[a.name]}")
        elif self._is_reg(a) and isinstance(b, VReg):
            self._emit(f"    cmpq {self._vreg_asm(b)}, %{self._reg_map[a.name]}")
        else:
            self._emit(f"    movq {self._operand_to_asm(a)}, %rax")
            self._emit(f"    cmpq {self._operand_to_asm(b)}, %rax")

        # Direct conditional jump
        jcc = {
            Opcode.Q_CMP_LT: "jl", Opcode.Q_CMP_GT: "jg",
            Opcode.Q_CMP_LE: "jle", Opcode.Q_CMP_GE: "jge",
            Opcode.Q_CMP_EQ: "je", Opcode.Q_CMP_NE: "jne",
        }.get(cmp_instr.opcode, "je")
        self._emit(f"    {jcc} .L_{target.name}")

    def _emit_jump(self, instr: QInstruction) -> None:
        target = instr.operands[0]
        self._emit(f"    jmp .L_{target.name}")

    def _emit_jump_if(self, instr: QInstruction, negate: bool) -> None:
        target = instr.dest
        cond = instr.src1
        if self._is_reg(cond):
            r = self._reg_map[cond.name]
            self._emit(f"    testq %{r}, %{r}")
        else:
            self._emit(f"    movq {self._vreg_asm(cond)}, %rax")
            self._emit("    testq %rax, %rax")
        jmp = "je" if negate else "jne"
        self._emit(f"    {jmp} .L_{target.name}")

    def _emit_label(self, instr: QInstruction) -> None:
        name = instr.operands[0].name if instr.operands else "unknown"
        self._emit(f".L_{name}:")

    def _emit_call(self, instr: QInstruction) -> None:
        func_label = instr.src1
        result_reg = instr.dest
        # Save caller-saved allocated regs before call
        caller_saved_used = []
        for vn, reg in self._reg_map.items():
            if reg in ("r8", "r9", "r10", "r11"):
                caller_saved_used.append((vn, reg))
        for _, reg in caller_saved_used:
            self._emit(f"    pushq %{reg}")
        # Set up argument
        if instr.src2 is not None:
            self._emit(f"    movq {self._operand_to_asm(instr.src2)}, %rdi")
        self._emit(f"    callq _vir_{func_label.name}")
        # Restore caller-saved
        for _, reg in reversed(caller_saved_used):
            self._emit(f"    popq %{reg}")
        # Store result
        if isinstance(result_reg, VReg):
            if self._is_reg(result_reg):
                dr = self._reg_map[result_reg.name]
                if dr != "rax":
                    self._emit(f"    movq %rax, %{dr}")
            else:
                self._emit(f"    movq %rax, {self._vreg_asm(result_reg)}")

    def _emit_ret(self, instr: QInstruction) -> None:
        if instr.operands:
            op = instr.operands[0]
            if isinstance(op, VReg) and self._is_reg(op):
                r = self._reg_map[op.name]
                if r != "rax":
                    self._emit(f"    movq %{r}, %rax")
            else:
                self._emit(f"    movq {self._operand_to_asm(op)}, %rax")
        # Restore spill space
        if self._spill_count > 0:
            aligned = (self._spill_count * 8 + 15) & ~15
            self._emit(f"    addq ${aligned}, %rsp")
        # Restore callee-saved
        for reg in reversed(sorted(self._used_callee_saved)):
            self._emit(f"    popq %{reg}")
        self._emit("    popq %rbp")
        self._emit("    retq")

    def _emit_print(self, instr: QInstruction) -> None:
        if not instr.operands:
            return
        val = instr.operands[0]
        self._emit(f"    movq {self._operand_to_asm(val)}, %rsi")
        self._emit("    leaq _fmt_int(%rip), %rdi")
        self._emit("    xorl %eax, %eax")
        self._emit("    callq _printf")
