#!/usr/bin/env python3
"""
meta_compiler.py — Phase 2 B2: Metadata-Driven Code Generator
================================================================
Reads opcode_metadata.json + arch config JSONs → generates C lookup tables
and dispatch helpers for the Vir codegen backend.

Outputs:
  src/generated/cost_table_arm64.h
  src/generated/cost_table_x86_64.h
  src/generated/cost_table_rv64.h
  src/generated/opcode_dispatch.h

Usage:
  python scripts/meta_compiler.py
  python scripts/meta_compiler.py --metadata ../opcode_metadata.json
  python scripts/meta_compiler.py --arch arm64
"""

from __future__ import annotations

import argparse
import json
import os
import textwrap
from datetime import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DEFAULT_METADATA = PROJECT_ROOT.parent / "opcode_metadata.json"
ARCH_DIR = PROJECT_ROOT / "data" / "arch"
OUTPUT_DIR = PROJECT_ROOT / "src" / "generated"


def load_json(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def emit_header_guard(name: str) -> tuple[str, str]:
    guard = f"VIR_GENERATED_{name.upper()}_H"
    top = f"#ifndef {guard}\n#define {guard}\n"
    bot = f"\n#endif /* {guard} */\n"
    return top, bot


def generate_cost_table(arch: str, config: dict, metadata: dict) -> str:
    """Generate per-architecture cost table C header."""
    guard_top, guard_bot = emit_header_guard(f"cost_table_{arch}")
    ts = datetime.now().isoformat()

    lines = [
        f"/* AUTO-GENERATED by meta_compiler.py — {ts} */",
        f"/* Architecture: {arch} */",
        "",
        guard_top,
        '#include <stdint.h>',
        "",
        "typedef struct {",
        "    const char *mnemonic;",
        "    uint8_t     latency;",
        "    uint8_t     throughput_x10;  /* throughput * 10 */",
        "    uint8_t     uops;",
        "    uint8_t     category;        /* 0=alu,1=mul,2=div,3=load,4=store,5=branch,6=simd,7=nop */",
        f"}} vir_instr_cost_{arch}_t;",
        "",
    ]

    cat_map = {
        "arith": 0, "alu": 0, "alu_int": 0,
        "mul": 1, "mul_int": 1,
        "div": 2, "div_int": 2,
        "load": 3, "load_gpr": 3, "load_simd": 3,
        "store": 4, "store_gpr": 4, "store_simd": 4,
        "branch": 5, "call": 5,
        "simd": 6, "simd_alu": 6, "simd_mul": 6, "simd_load": 6, "simd_store": 6,
        "nop": 7, "syscall": 5,
    }

    instructions = config.get("instructions", [])

    lines.append(f"static const vir_instr_cost_{arch}_t VIR_COST_{arch.upper()}[] = {{")

    for instr in instructions:
        mnem = instr.get("mnemonic", "???")
        lat = instr.get("latency", 1)
        tp = instr.get("throughput", 1.0)
        uops = instr.get("uops", 1)
        cat_str = instr.get("category", "alu")
        cat = cat_map.get(cat_str, 0)
        tp_x10 = int(tp * 10)
        lines.append(f'    {{ "{mnem}", {lat}, {tp_x10}, {uops}, {cat} }},')

    lines.append("};")
    lines.append(f"#define VIR_COST_{arch.upper()}_COUNT {len(instructions)}")
    lines.append("")

    # Q-IR → native instruction mapping
    qir_map = config.get("qir_map", {})
    if qir_map:
        lines.append(f"/* Q-IR opcode → native mnemonic mapping */")
        lines.append(f"typedef struct {{")
        lines.append(f"    const char *qir_opcode;")
        lines.append(f"    const char *native_mnemonic;")
        lines.append(f"    uint8_t     latency;")
        lines.append(f"    uint8_t     clobber_flags;  /* bit0=nzcv, bit1=mem */")
        lines.append(f"}} vir_qir_map_{arch}_t;")
        lines.append(f"")
        lines.append(f"static const vir_qir_map_{arch}_t VIR_QIR_MAP_{arch.upper()}[] = {{")

        for qir_op, mapping in sorted(qir_map.items()):
            if isinstance(mapping, dict):
                native = mapping.get("maps_to", [mapping.get("mnemonic", "?")])
                if isinstance(native, list):
                    native = native[0] if native else "?"
                lat = mapping.get("latency", 1)
                clobber = 1 if mapping.get("clobbers_flags", False) else 0
            elif isinstance(mapping, str):
                native = mapping
                lat = 1
                clobber = 0
            else:
                continue
            lines.append(f'    {{ "{qir_op}", "{native}", {lat}, {clobber} }},')

        lines.append("};")
        lines.append(f"#define VIR_QIR_MAP_{arch.upper()}_COUNT {len(qir_map)}")
        lines.append("")

    # Pipeline info
    lines.append(f"/* Pipeline characteristics */")
    lines.append(f"#define VIR_{arch.upper()}_ISSUE_WIDTH      {config.get('issue_width', 4)}")
    lines.append(f"#define VIR_{arch.upper()}_ROB_SIZE          {config.get('reorder_buffer', 256)}")
    lines.append(f"#define VIR_{arch.upper()}_PHYS_INT_REGS     {config.get('phys_int_regs', 128)}")
    lines.append(f"#define VIR_{arch.upper()}_PHYS_FP_REGS      {config.get('phys_fp_regs', 128)}")
    lines.append("")

    # Spill cost info
    spill = config.get("spill", {})
    if spill:
        lines.append(f"#define VIR_{arch.upper()}_SPILL_STORE_COST  {spill.get('spill_store', 1)}")
        lines.append(f"#define VIR_{arch.upper()}_SPILL_LOAD_COST   {spill.get('spill_load', 4)}")
        lines.append(f"#define VIR_{arch.upper()}_SPILL_TOTAL_COST  {spill.get('total', 5)}")
        lines.append("")

    lines.append(guard_bot)
    return "\n".join(lines)


def generate_opcode_dispatch(metadata: dict) -> str:
    """Generate unified opcode dispatch header from opcode_metadata.json."""
    guard_top, guard_bot = emit_header_guard("opcode_dispatch")
    ts = datetime.now().isoformat()

    lines = [
        f"/* AUTO-GENERATED by meta_compiler.py — {ts} */",
        f"/* Unified Q-IR opcode cost model & traits */",
        "",
        guard_top,
        '#include <stdint.h>',
        '#include <stdbool.h>',
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint8_t     default_latency;",
        "    uint8_t     default_throughput_x10;",
        "    uint8_t     instr_class;     /* 0=alu,1=mul,2=div,3=load,4=store,5=branch,6=simd,7=nop */",
        "    bool        has_side_effects;",
        "    bool        is_pure;",
        "    bool        is_commutative;",
        "    bool        is_associative;",
        "    bool        clobbers_flags;",
        "    bool        touches_memory;",
        "} vir_opcode_meta_t;",
        "",
    ]

    class_map = {
        "alu_int": 0, "mul_int": 1, "div_int": 2,
        "load_gpr": 3, "store_gpr": 4, "branch": 5, "call": 5,
        "simd_alu": 6, "simd_mul": 6, "simd_load": 6, "simd_store": 6,
        "nop": 7, "syscall": 5,
    }

    opcodes = metadata.get("opcodes", {})
    instr_classes = metadata.get("instruction_classes", {})

    lines.append("static const vir_opcode_meta_t VIR_OPCODE_META[] = {")

    for op_name, op_data in sorted(opcodes.items()):
        ic = op_data.get("instruction_class", "alu_int")
        cls_num = class_map.get(ic, 0)

        ic_data = instr_classes.get(ic, {})
        lat = ic_data.get("latency", op_data.get("latency", 1))
        tp = ic_data.get("throughput", op_data.get("throughput", 1.0))
        tp_x10 = int(tp * 10)

        side_fx = op_data.get("side_effects", {})
        has_se = any(side_fx.values()) if isinstance(side_fx, dict) else bool(side_fx)
        touches_mem = side_fx.get("memory", False) if isinstance(side_fx, dict) else False

        traits = op_data.get("optimizer_traits", {})
        pure = traits.get("pure", False)
        comm = traits.get("commutative", False)
        assoc = traits.get("associative", False)

        clobber = op_data.get("clobber", {})
        clob_flags = "nzcv" in str(clobber)

        b = lambda v: "true" if v else "false"
        lines.append(
            f'    {{ "{op_name}", {lat}, {tp_x10}, {cls_num}, '
            f'{b(has_se)}, {b(pure)}, {b(comm)}, {b(assoc)}, '
            f'{b(clob_flags)}, {b(touches_mem)} }},'
        )

    lines.append("};")
    lines.append(f"#define VIR_OPCODE_META_COUNT {len(opcodes)}")
    lines.append("")

    # Generate a fast lookup by opcode enum value
    lines.append("/* Fast lookup: opcode enum → index into VIR_OPCODE_META[] */")
    lines.append("/* Usage: VIR_OPCODE_META[vir_opcode_meta_index(opcode)] */")
    lines.append("static inline int vir_opcode_meta_index(const char *opcode_name) {")
    lines.append("    for (int i = 0; i < VIR_OPCODE_META_COUNT; i++) {")
    lines.append("        const char *a = opcode_name, *b = VIR_OPCODE_META[i].name;")
    lines.append("        int match = 1;")
    lines.append("        while (*a && *b) { if (*a++ != *b++) { match = 0; break; } }")
    lines.append("        if (match && *a == *b) return i;")
    lines.append("    }")
    lines.append("    return -1;")
    lines.append("}")
    lines.append("")

    lines.append(guard_bot)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Vir Meta-Compiler: generate C cost tables from metadata"
    )
    parser.add_argument("--metadata", type=Path, default=DEFAULT_METADATA,
                        help="Path to opcode_metadata.json")
    parser.add_argument("--arch-dir", type=Path, default=ARCH_DIR,
                        help="Directory containing arch config JSONs")
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR,
                        help="Output directory for generated headers")
    parser.add_argument("--arch", choices=["arm64", "x86_64", "rv64", "all"],
                        default="all")
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Load opcode metadata
    if args.metadata.exists():
        metadata = load_json(args.metadata)
        print(f"Loaded opcode metadata: {len(metadata.get('opcodes', {}))} opcodes")
    else:
        print(f"Warning: {args.metadata} not found, generating dispatch with empty opcodes")
        metadata = {"opcodes": {}, "instruction_classes": {}}

    # Generate per-arch cost tables
    arch_files = {
        "arm64": "arm64_config.json",
        "x86_64": "x86_64_config.json",
        "rv64": "rv64_config.json",
    }

    for arch, fname in arch_files.items():
        if args.arch not in (arch, "all"):
            continue
        config_path = args.arch_dir / fname
        if not config_path.exists():
            print(f"  Skip {arch}: {config_path} not found")
            continue
        config = load_json(config_path)
        code = generate_cost_table(arch, config, metadata)
        out_path = args.output_dir / f"cost_table_{arch}.h"
        out_path.write_text(code)
        n_instr = len(config.get("instructions", []))
        n_qir = len(config.get("qir_map", {}))
        print(f"  {arch}: {n_instr} instructions, {n_qir} QIR mappings → {out_path}")

    # Generate unified opcode dispatch
    if args.arch == "all" or True:
        code = generate_opcode_dispatch(metadata)
        out_path = args.output_dir / "opcode_dispatch.h"
        out_path.write_text(code)
        print(f"  dispatch: {len(metadata.get('opcodes', {}))} opcodes → {out_path}")

    print(f"\nDone. Generated files in {args.output_dir}/")


if __name__ == "__main__":
    main()
