"""
cost_model.py – Architecture-Aware Instruction Cost Model for Vir
==================================================================
Loads arch_config.json (generated by micro-prober + LLVM parser)
and provides cost queries for the optimizer and codegen.

Key features:
  - Per-opcode latency, throughput, micro-op count
  - Branch misprediction penalty
  - Memory hierarchy costs
  - Register spill cost estimation
  - Basic block and function cost estimation
  - Variant cost comparison for multi-versioning

Usage:
    from src.ir.cost_model import CostModel
    cm = CostModel("arm64")
    print(cm.latency(Opcode.Q_MUL))   # → 3
    print(cm.block_cost(instrs))       # → 42.5
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Sequence

from src.ir.instructions.q_ir import Opcode, QInstruction, QFunction, VReg


# ═══════════════════════════════════════════════════════════
# Data Structures
# ═══════════════════════════════════════════════════════════

@dataclass(frozen=True)
class InstrCostEntry:
    """Cost entry for a single Q-IR opcode mapped to native instruction."""
    opcode: Opcode
    mnemonic: str         # native instruction name (e.g. "ADD", "SDIV")
    latency: int          # cycles from input ready to output ready
    throughput: float     # instructions per cycle (reciprocal throughput)
    uops: int             # micro-ops consumed
    category: str         # "arith", "mul", "div", "load", "store", "branch", "cmp"
    sched_class: str = ""  # scheduling class hint (INT_ALU, INT_MUL, etc.)


@dataclass(frozen=True)
class BranchCostInfo:
    predict_hit: float
    predict_miss: float
    miss_penalty: float


@dataclass(frozen=True)
class MemoryCostInfo:
    l1_latency: float
    l2_latency: float
    l3_latency: float
    mem_latency: float
    store_latency: float


@dataclass(frozen=True)
class SpillCostInfo:
    spill_store: int
    spill_load: int
    total: int


@dataclass(frozen=True)
class CacheTopology:
    """Runtime cache topology from cpu_caps."""
    cache_line_size: int = 64
    l1d_size_kb: int = 64
    l1d_assoc: int = 8
    l1i_size_kb: int = 128
    l2_size_kb: int = 4096
    l2_assoc: int = 16
    l3_size_kb: int = 0
    l3_assoc: int = 0


@dataclass(frozen=True)
class TLBInfo:
    """TLB parameters for memory hierarchy model."""
    page_size: int = 16384
    l1_dtlb_entries: int = 256
    l1_itlb_entries: int = 192
    l2_tlb_entries: int = 4096
    huge_page_size: int = 33554432  # 32MB


@dataclass(frozen=True)
class PrefetchConfig:
    """Prefetch parameters for data locality optimization."""
    hw_prefetch_distance: int = 16      # cache lines
    sw_prefetch: bool = True
    prefetch_hint_size: int = 512       # bytes
    optimal_stride: int = 64            # bytes (1 cache line)


@dataclass(frozen=True)
class PackCostInfo:
    """Cost of packing/unpacking scalar data to/from SIMD registers.

    When vectorizing, GPR scalar values must be moved into vector
    registers (packing) and results extracted back (unpacking).
    This overhead can negate SIMD benefits for short sequences.
    """
    pack_latency: int = 3       # cycles to INS/DUP scalar → vector lane
    unpack_latency: int = 2     # cycles to UMOV/extract lane → scalar
    lanes_per_pack: int = 1     # how many lanes one pack op fills
    alignment_penalty: float = 1.5  # multiplier for unaligned access


# ═══════════════════════════════════════════════════════════
# Cost Model
# ═══════════════════════════════════════════════════════════

class CostModel:
    """
    Architecture-aware cost model for Q-IR instructions.

    Loads cost data from arch_config.json files generated by the
    micro-prober and LLVM TableGen parser.
    """

    # Default config file locations (relative to project root)
    _CONFIG_PATHS = {
        "arm64":  "data/arch/arm64_config.json",
        "x86_64": "data/arch/x86_64_config.json",
        "rv64":   "data/arch/rv64_config.json",
    }

    def __init__(self, arch: str = "arm64", config_path: Optional[str] = None) -> None:
        self.arch = arch
        self._costs: dict[Opcode, InstrCostEntry] = {}
        self.branch = BranchCostInfo(1.0, 14.0, 13.0)
        self.memory = MemoryCostInfo(4.0, 12.0, 40.0, 200.0, 1.0)
        self.spill = SpillCostInfo(1, 4, 5)
        self.issue_width: int = 4
        self.cpu: str = "unknown"
        self.cache = CacheTopology()
        self.tlb = TLBInfo()
        self.prefetch = PrefetchConfig()
        self.pack_cost = PackCostInfo()
        self.max_simd_width: int = 16  # bytes (128-bit default)
        self.min_vectorize_count: int = 8  # minimum elements to justify SIMD
        # Per-opcode optimizer traits loaded from metadata
        self._traits: dict[str, dict] = {}  # opcode_name -> {pure, commutative, ...}

        # Locate config file
        if config_path:
            cfg_file = Path(config_path)
        else:
            # Try relative to this file (src/ir/cost_model/) → project root
            project_root = Path(__file__).resolve().parent.parent.parent.parent
            cfg_file = project_root / self._CONFIG_PATHS.get(arch, "")

        if cfg_file.exists():
            self._load_config(cfg_file)
        else:
            # Fall back to hardcoded defaults
            self._load_defaults()

        # Attempt to overlay opcode_metadata.json for refined heuristics
        self._try_load_opcode_metadata()

    def _load_config(self, path: Path) -> None:
        """Load cost model from arch_config.json."""
        with open(path) as f:
            data = json.load(f)

        self.cpu = data.get("cpu", "unknown")
        self.issue_width = data.get("issue_width", 4)

        # Build Q-IR → mnemonic mapping
        qir_map: dict[str, str] = data.get("qir_map", {})
        # Build mnemonic → cost lookup from instructions array
        mnemonic_costs: dict[str, dict] = {}
        for entry in data.get("instructions", []):
            mnemonic_costs[entry["mnemonic"]] = entry

        # Map each Q-IR opcode
        for opcode in Opcode:
            qir_name = opcode.name  # e.g. "Q_ADD"
            mnemonic = qir_map.get(qir_name, "NOP")
            cost_data = mnemonic_costs.get(mnemonic, {})

            self._costs[opcode] = InstrCostEntry(
                opcode=opcode,
                mnemonic=mnemonic,
                latency=cost_data.get("latency", 1),
                throughput=cost_data.get("throughput", 1.0),
                uops=cost_data.get("uops", 1),
                category=cost_data.get("category", "arith"),
            )

        # Load branch, memory, spill costs
        br = data.get("branch", {})
        if br:
            self.branch = BranchCostInfo(
                predict_hit=br.get("predict_hit", 1.0),
                predict_miss=br.get("predict_miss", 14.0),
                miss_penalty=br.get("miss_penalty", 13.0),
            )

        mem = data.get("memory", {})
        if mem:
            self.memory = MemoryCostInfo(
                l1_latency=mem.get("l1_latency", 4.0),
                l2_latency=mem.get("l2_latency", 12.0),
                l3_latency=mem.get("l3_latency", 40.0),
                mem_latency=mem.get("mem_latency", 200.0),
                store_latency=mem.get("store_latency", 1.0),
            )

        sp = data.get("spill", {})
        if sp:
            self.spill = SpillCostInfo(
                spill_store=sp.get("spill_store", 1),
                spill_load=sp.get("spill_load", 4),
                total=sp.get("total", 5),
            )

    def _load_defaults(self) -> None:
        """Hardcoded fallback costs aligned with opcode_metadata.json heuristics.

        Latency/throughput values are practical compiler heuristics for
        Apple Silicon cost modelling, not hardware ground truth.  They
        originate from publicly-available measurement /reverse engineering
        and Apple’s optimisation guides.
        """
        defaults = {
            # ---- data movement / immediates ----
            Opcode.Q_LOAD:         ("MOV",    1, 2.0, 1, "arith",  "MOVE"),
            Opcode.Q_STORE:        ("STR",    1, 2.0, 1, "store",  "STORE"),
            Opcode.Q_MOVE:         ("MOV",    0, 4.0, 1, "arith",  "MOVE"),
            Opcode.Q_LOAD_STRING:  ("ADRP",   2, 1.0, 1, "load",   "ADDR_GEN"),
            # ---- integer ALU (lat=1, 2/cycle) ----
            Opcode.Q_ADD:          ("ADD",    1, 2.0, 1, "arith",  "INT_ALU"),
            Opcode.Q_SUB:          ("SUB",    1, 2.0, 1, "arith",  "INT_ALU"),
            # ---- integer MUL (lat=3, 1/cycle) ----
            Opcode.Q_MUL:          ("MUL",    3, 1.0, 1, "mul",    "INT_MUL"),
            # ---- integer DIV (lat=8, 0.25/cycle) ----
            Opcode.Q_DIV:          ("SDIV",   8, 0.25, 1, "div",   "INT_DIV"),
            Opcode.Q_MOD:          ("SDIV+MSUB", 10, 0.2, 2, "div", "INT_DIV"),
            # ---- compare (lat=1, 2/cycle) ----
            Opcode.Q_CMP_EQ:       ("CMP",    1, 2.0, 1, "cmp",   "INT_ALU"),
            Opcode.Q_CMP_NE:       ("CMP",    1, 2.0, 1, "cmp",   "INT_ALU"),
            Opcode.Q_CMP_GT:       ("CMP",    1, 2.0, 1, "cmp",   "INT_ALU"),
            Opcode.Q_CMP_LT:       ("CMP",    1, 2.0, 1, "cmp",   "INT_ALU"),
            Opcode.Q_CMP_GE:       ("CMP",    1, 2.0, 1, "cmp",   "INT_ALU"),
            Opcode.Q_CMP_LE:       ("CMP",    1, 2.0, 1, "cmp",   "INT_ALU"),
            # ---- branches ----
            Opcode.Q_JUMP:         ("B",      1, 1.0, 1, "branch", "BRANCH"),
            Opcode.Q_JUMP_IF:      ("B.cond", 1, 1.0, 1, "branch", "BRANCH"),
            Opcode.Q_JUMP_IF_NOT:  ("B.cond", 1, 1.0, 1, "branch", "BRANCH"),
            Opcode.Q_CALL:         ("BL",     3, 0.5, 1, "branch", "CALL"),
            Opcode.Q_RET:          ("RET",    1, 1.0, 1, "branch", "RET"),
            # ---- I/O  (treated as runtime calls) ----
            Opcode.Q_PRINT:        ("BL",    30, 0.03,1, "branch", "CALL_IO"),
            Opcode.Q_INPUT:        ("BL",    30, 0.03,1, "branch", "CALL_IO"),
            Opcode.Q_HALT:         ("BRK",  100, 0.01,1, "branch", "TRAP"),
            # ---- pseudo / misc ----
            Opcode.Q_LABEL:        ("NOP",    0, 8.0, 0, "arith",  "PSEUDO"),
            Opcode.Q_NOP:          ("NOP",    0, 8.0, 0, "arith",  "NONE"),
            Opcode.Q_PATCH_POINT:  ("NOP",    0, 8.0, 0, "arith",  "PATCH_POINT"),
            # ---- SIMD (NEON) ----
            Opcode.Q_VLOAD:        ("LDR_Q",  4, 2.0, 1, "simd_load",  "SIMD_LOAD"),
            Opcode.Q_VSTORE:       ("STR_Q",  1, 2.0, 1, "simd_store", "SIMD_STORE"),
            Opcode.Q_VADD:         ("ADD_v",  2, 2.0, 1, "simd_arith", "SIMD_ALU"),
            Opcode.Q_VSUB:         ("SUB_v",  2, 2.0, 1, "simd_arith", "SIMD_ALU"),
            Opcode.Q_VMUL:         ("MUL_v",  3, 1.0, 1, "simd_mul",   "SIMD_MUL"),
            Opcode.Q_VFMA:         ("FMLA_v", 4, 1.0, 1, "simd_mul",   "SIMD_MUL"),
            Opcode.Q_VDIV:         ("FDIV_v",12, 0.25,1, "simd_div",   "SIMD_DIV"),
            Opcode.Q_VMIN:         ("MIN_v",  2, 2.0, 1, "simd_arith", "SIMD_ALU"),
            Opcode.Q_VMAX:         ("MAX_v",  2, 2.0, 1, "simd_arith", "SIMD_ALU"),
            Opcode.Q_VREDUCE:      ("ADDV",   3, 1.0, 1, "simd_reduce","SIMD_REDUCE"),
            Opcode.Q_VSPLAT:       ("DUP_v",  2, 2.0, 1, "simd_perm",  "SIMD_SHUFFLE"),
            Opcode.Q_VPERM:        ("TBL_v",  2, 2.0, 1, "simd_perm",  "SIMD_SHUFFLE"),
            # ---- scalar FP ----
            Opcode.Q_FLOAD:        ("FMOV",   2, 2.0, 1, "fp_load",  "FP_MOVE"),
            Opcode.Q_FSTORE:       ("STR_D",  1, 2.0, 1, "fp_store", "STORE"),
            Opcode.Q_FMOVE:        ("FMOV",   0, 4.0, 1, "fp_arith", "FP_MOVE"),
            Opcode.Q_FADD:         ("FADD",   2, 2.0, 1, "fp_arith", "FP_ALU"),
            Opcode.Q_FSUB:         ("FSUB",   2, 2.0, 1, "fp_arith", "FP_ALU"),
            Opcode.Q_FMUL:         ("FMUL",   3, 1.0, 1, "fp_mul",   "FP_MUL"),
            Opcode.Q_FDIV:         ("FDIV",  10, 0.25,1, "fp_div",   "FP_DIV"),
            Opcode.Q_FCMP_EQ:      ("FCMP",   1, 2.0, 1, "fp_cmp",   "FP_ALU"),
            Opcode.Q_FCMP_LT:      ("FCMP",   1, 2.0, 1, "fp_cmp",   "FP_ALU"),
            Opcode.Q_FCMP_GT:      ("FCMP",   1, 2.0, 1, "fp_cmp",   "FP_ALU"),
            Opcode.Q_FCVT_I2F:     ("SCVTF",  3, 1.0, 1, "fp_cvt",   "FP_CVT"),
            Opcode.Q_FCVT_F2I:     ("FCVTZS", 3, 1.0, 1, "fp_cvt",   "FP_CVT"),
        }
        for opcode, vals in defaults.items():
            mnem, lat, thr, uops, cat, sclass = vals
            self._costs[opcode] = InstrCostEntry(
                opcode=opcode, mnemonic=mnem, latency=lat,
                throughput=thr, uops=uops, category=cat,
                sched_class=sclass,
            )

    # ── Opcode Metadata Loader ───────────────────────────────

    # Map instruction_class strings from metadata → category strings used here
    _CLASS_TO_CATEGORY: dict[str, str] = {
        "alu_int": "arith", "mul_int": "mul", "div_int": "div",
        "load_gpr": "load", "store_gpr": "store",
        "branch": "branch", "call": "branch", "syscall": "branch",
        "simd_alu": "simd_arith", "simd_mul": "simd_mul",
        "simd_load": "simd_load", "simd_store": "simd_store",
        "nop": "arith",
    }

    def _try_load_opcode_metadata(self) -> None:
        """Attempt to locate and load opcode_metadata.json.

        Searches (in order):
          1. project_root / opcode_metadata.json
          2. project_root / .. / opcode_metadata.json  (monorepo workspace)
        If found, overlays per-opcode costs and records optimizer traits.
        """
        project_root = Path(__file__).resolve().parent.parent.parent.parent
        candidates = [
            project_root / "opcode_metadata.json",
            project_root.parent / "opcode_metadata.json",
        ]
        for p in candidates:
            if p.exists():
                self._load_opcode_metadata(p)
                return

    def _load_opcode_metadata(self, path: Path) -> None:
        """Load opcode_metadata.json and overlay costs + traits."""
        with open(path) as f:
            data = json.load(f)

        opcodes_data: dict = data.get("opcodes", {})
        instruction_classes: dict = data.get("instruction_classes", {})

        for name, info in opcodes_data.items():
            # Resolve the Opcode enum member
            try:
                opcode = Opcode[name]
            except KeyError:
                continue  # metadata has an opcode we don't model yet

            lat = info.get("latency_cycles_est")
            thr = info.get("throughput_per_cycle_est")
            sclass = info.get("sched_class", "")
            iclass = info.get("instruction_class", "")

            # Derive category from instruction_class
            category = self._CLASS_TO_CATEGORY.get(iclass, "arith")

            # Native mnemonic: prefer maps_to, fall back to existing
            maps_to = info.get("maps_to", "")
            if isinstance(maps_to, list):
                maps_to = "+".join(maps_to)  # e.g. ["SDIV", "MSUB"] → "SDIV+MSUB"
            existing = self._costs.get(opcode)

            mnem = maps_to or (existing.mnemonic if existing else "NOP")
            # Preserve existing values when metadata fields are absent
            final_lat = lat if lat is not None else (existing.latency if existing else 1)
            final_thr = thr if thr is not None else (existing.throughput if existing else 1.0)
            final_uops = existing.uops if existing else 1
            final_cat = category if iclass else (existing.category if existing else "arith")

            self._costs[opcode] = InstrCostEntry(
                opcode=opcode, mnemonic=mnem, latency=final_lat,
                throughput=final_thr, uops=final_uops,
                category=final_cat, sched_class=sclass,
            )

            # Record optimizer traits for passes (CSE, DCE, LICM, etc.)
            traits = info.get("optimizer_traits", {})
            if traits:
                self._traits[name] = traits

    def load_opcode_metadata(self, path: str) -> None:
        """Public API: explicitly load opcode metadata from a given path."""
        self._load_opcode_metadata(Path(path))

    # ── Public API: Optimizer Trait Queries ───────────────────

    def is_pure(self, opcode: Opcode) -> bool:
        """True if the opcode has no side effects and is deterministic."""
        return self._traits.get(opcode.name, {}).get("pure", False)

    def is_commutative(self, opcode: Opcode) -> bool:
        """True if operand order doesn't affect the result."""
        return self._traits.get(opcode.name, {}).get("commutative", False)

    def is_associative(self, opcode: Opcode) -> bool:
        """True if the operation is associative (enables reassociation)."""
        return self._traits.get(opcode.name, {}).get("associative", False)

    def is_speculatable(self, opcode: Opcode) -> bool:
        """True if the opcode can be safely hoisted past branches."""
        return self._traits.get(opcode.name, {}).get("speculatable", False)

    def is_coalescable(self, opcode: Opcode) -> bool:
        """True if the opcode can be eliminated by register coalescing."""
        return self._traits.get(opcode.name, {}).get("coalescable", False)

    def is_hoistable(self, opcode: Opcode) -> bool:
        """True if the opcode is safe to hoist out of loops."""
        return self._traits.get(opcode.name, {}).get("hoistable", False)

    def is_erasable(self, opcode: Opcode) -> bool:
        """True if the opcode can be deleted when result is unused."""
        return self._traits.get(opcode.name, {}).get("erasable", False)

    def pure_opcodes(self) -> frozenset[Opcode]:
        """Return the set of opcodes marked as pure (for CSE)."""
        result = set()
        for name, traits in self._traits.items():
            if traits.get("pure", False):
                try:
                    result.add(Opcode[name])
                except KeyError:
                    pass
        return frozenset(result)

    def commutative_opcodes(self) -> frozenset[Opcode]:
        """Return the set of opcodes marked as commutative (for CSE normalization)."""
        result = set()
        for name, traits in self._traits.items():
            if traits.get("commutative", False):
                try:
                    result.add(Opcode[name])
                except KeyError:
                    pass
        return frozenset(result)

    def speculatable_opcodes(self) -> frozenset[Opcode]:
        """Return the set of opcodes that can be speculated (for LICM)."""
        result = set()
        for name, traits in self._traits.items():
            if traits.get("speculatable", False):
                try:
                    result.add(Opcode[name])
                except KeyError:
                    pass
        return frozenset(result)

    def scheduling_class(self, opcode: Opcode) -> str:
        """Get the scheduling class for instruction scheduling."""
        entry = self._costs.get(opcode)
        return entry.sched_class if entry else ""

    # ── Public API: Per-Instruction Queries ──────────────────

    def get(self, opcode: Opcode) -> InstrCostEntry:
        """Get the full cost entry for an opcode."""
        return self._costs.get(opcode, InstrCostEntry(
            opcode=opcode, mnemonic="NOP", latency=1,
            throughput=1.0, uops=1, category="arith",
        ))

    def latency(self, opcode: Opcode) -> int:
        """Get execution latency in cycles for an opcode."""
        return self.get(opcode).latency

    def throughput(self, opcode: Opcode) -> float:
        """Get throughput (IPC) for an opcode."""
        return self.get(opcode).throughput

    def is_expensive(self, opcode: Opcode, threshold: int = 4) -> bool:
        """Check if an instruction is expensive (latency >= threshold)."""
        return self.latency(opcode) >= threshold

    def reciprocal_throughput(self, opcode: Opcode) -> float:
        """Reciprocal throughput = 1/IPC (cycles per op at max throughput)."""
        t = self.throughput(opcode)
        return 1.0 / t if t > 0 else float('inf')

    # ── Public API: Block/Function Cost Estimation ───────────

    def instr_cost(self, instr: QInstruction) -> float:
        """Estimate the cost of a single Q-IR instruction in cycles.
        
        Uses latency as the primary metric, but adds extra cost for
        memory operations and branch misprediction.
        """
        entry = self.get(instr.opcode)
        cost = float(entry.latency)

        # Memory operations: use L1 latency for loads, store latency for stores
        if entry.category == "load":
            cost = self.memory.l1_latency
        elif entry.category == "store":
            cost = self.memory.store_latency

        # Branch: add average misprediction penalty (assume 10% miss rate)
        if entry.category == "branch" and instr.opcode in (
            Opcode.Q_JUMP_IF, Opcode.Q_JUMP_IF_NOT,
        ):
            cost += 0.10 * self.branch.miss_penalty

        return cost

    def block_cost(self, instrs: Sequence[QInstruction]) -> float:
        """Estimate total cost for a basic block (sum of instruction costs).
        
        This gives a rough serial cost. For more accurate modeling,
        use throughput_cost() which accounts for ILP.
        """
        return sum(self.instr_cost(i) for i in instrs)

    def throughput_cost(self, instrs: Sequence[QInstruction]) -> float:
        """Estimate throughput-bound cost (accounts for instruction-level parallelism).
        
        The throughput cost is: max(total_uops / issue_width, max_port_pressure).
        Simplified: sum of reciprocal throughputs.
        """
        total = 0.0
        for instr in instrs:
            total += self.reciprocal_throughput(instr.opcode)
        return total

    def function_cost(self, func: QFunction) -> float:
        """Estimate total function cost."""
        return self.block_cost(func.body)

    # ── Public API: Optimization Decision Helpers ────────────

    def should_strength_reduce(self, opcode: Opcode) -> bool:
        """Should we try to replace this operation with a cheaper one?
        
        Useful for: MUL by power-of-2 → shift, DIV by constant → mul+shift.
        """
        return self.latency(opcode) >= 3

    def spill_cost_estimate(self, num_spills: int) -> float:
        """Estimate cost of N register spills (store + future reload)."""
        return num_spills * self.spill.total

    def variant_cost_ratio(
        self,
        safe_instrs: Sequence[QInstruction],
        fast_instrs: Sequence[QInstruction],
    ) -> float:
        """Compare safe vs fast variant cost.
        
        Returns ratio: safe_cost / fast_cost.
        Values > 1.0 mean safe is slower (expected).
        """
        safe_cost = self.block_cost(safe_instrs)
        fast_cost = self.block_cost(fast_instrs)
        if fast_cost == 0:
            return float('inf')
        return safe_cost / fast_cost

    def div_is_worth_strength_reduce(self, divisor: Optional[int]) -> bool:
        """Check if dividing by a constant is worth replacing with mul+shift.
        
        DIV latency (~8-20 cycles) vs MUL+SHIFT (~4 cycles).
        Always worthwhile when divisor is known at compile time.
        """
        if divisor is None:
            return False
        return True  # constant division is always worth replacing

    # ── Memory Hierarchy Model ───────────────────────────────

    def load_cache_topology(self, caps_json_path: Optional[str] = None) -> None:
        """Load cache topology from cpu_caps.json (auto-detected at runtime)."""
        if caps_json_path is None:
            project_root = Path(__file__).resolve().parent.parent.parent.parent
            caps_file = project_root / "data" / "arch" / "cpu_caps.json"
        else:
            caps_file = Path(caps_json_path)

        if not caps_file.exists():
            return

        with open(caps_file) as f:
            data = json.load(f)

        cache = data.get("cache", {})
        if cache:
            self.cache = CacheTopology(
                cache_line_size=cache.get("line_size", 64),
                l1d_size_kb=cache.get("l1d_size_kb", 64),
                l1d_assoc=cache.get("l1d_assoc", 8),
                l1i_size_kb=cache.get("l1i_size_kb", 128),
                l2_size_kb=cache.get("l2_size_kb", 4096),
                l2_assoc=cache.get("l2_assoc", 16),
                l3_size_kb=cache.get("l3_size_kb", 0),
                l3_assoc=cache.get("l3_assoc", 0),
            )

        tlb = data.get("tlb", {})
        if tlb:
            self.tlb = TLBInfo(
                page_size=tlb.get("page_size", 16384),
                l1_dtlb_entries=tlb.get("l1_dtlb_entries", 256),
                l1_itlb_entries=tlb.get("l1_itlb_entries", 192),
                l2_tlb_entries=tlb.get("l2_tlb_entries", 4096),
                huge_page_size=tlb.get("huge_page_size", 33554432),
            )

        pf = data.get("prefetch", {})
        if pf:
            self.prefetch = PrefetchConfig(
                hw_prefetch_distance=pf.get("hw_prefetch_distance", 16),
                sw_prefetch=pf.get("sw_prefetch", True),
                prefetch_hint_size=pf.get("prefetch_hint_size", 512),
            )

        simd = data.get("simd", {})
        if simd:
            self.max_simd_width = simd.get("max_simd_width", 16)
            # Derive pack cost from SIMD capabilities
            has_neon = simd.get("neon", False)
            if has_neon:
                self.pack_cost = PackCostInfo(
                    pack_latency=2, unpack_latency=2,
                    lanes_per_pack=1, alignment_penalty=1.0,
                )
            else:
                self.pack_cost = PackCostInfo(
                    pack_latency=3, unpack_latency=3,
                    lanes_per_pack=1, alignment_penalty=1.5,
                )

    def estimated_access_cost(self, working_set_kb: int) -> float:
        """Estimate average memory access cost based on working set size.

        Uses simple cache hierarchy model: if working set fits in L1,
        cost is L1 latency; if L2, weighted average, etc.
        """
        if working_set_kb <= self.cache.l1d_size_kb:
            return self.memory.l1_latency
        elif working_set_kb <= self.cache.l2_size_kb:
            l1_hit_rate = self.cache.l1d_size_kb / working_set_kb
            return (l1_hit_rate * self.memory.l1_latency +
                    (1 - l1_hit_rate) * self.memory.l2_latency)
        elif self.cache.l3_size_kb > 0 and working_set_kb <= self.cache.l3_size_kb:
            l2_hit_rate = self.cache.l2_size_kb / working_set_kb
            return (l2_hit_rate * self.memory.l2_latency +
                    (1 - l2_hit_rate) * self.memory.l3_latency)
        else:
            total_cache = self.cache.l3_size_kb or self.cache.l2_size_kb
            if total_cache > 0:
                cache_hit_rate = total_cache / working_set_kb
            else:
                cache_hit_rate = 0.0
            last_level = self.memory.l3_latency if self.cache.l3_size_kb > 0 else self.memory.l2_latency
            return (cache_hit_rate * last_level +
                    (1 - cache_hit_rate) * self.memory.mem_latency)

    def tlb_miss_cost(self, num_pages_touched: int) -> float:
        """Estimate TLB miss penalty for accessing a data structure.

        If num_pages_touched <= L1 dTLB entries, no misses.
        Otherwise, each extra page has some probability of TLB miss.
        """
        if num_pages_touched <= self.tlb.l1_dtlb_entries:
            return 0.0
        overflow = num_pages_touched - self.tlb.l1_dtlb_entries
        l2_coverage = self.tlb.l2_tlb_entries - self.tlb.l1_dtlb_entries
        if overflow <= l2_coverage:
            return overflow * 5.0  # ~5 cycles per L2 TLB hit
        extra = overflow - l2_coverage
        return l2_coverage * 5.0 + extra * 30.0  # page walk ~30 cycles

    def cache_lines_for(self, num_elements: int, element_bytes: int = 4) -> int:
        """Number of cache lines needed for a contiguous array."""
        total_bytes = num_elements * element_bytes
        cl = self.cache.cache_line_size or 64
        return (total_bytes + cl - 1) // cl

    def prefetch_distance_elements(self, element_bytes: int = 4) -> int:
        """Optimal prefetch distance in number of elements."""
        return self.prefetch.prefetch_hint_size // element_bytes

    # ── SIMD Vectorization Cost Model ────────────────────────

    def simd_lanes(self, element_bytes: int = 4) -> int:
        """Number of SIMD lanes for given element size."""
        return self.max_simd_width // element_bytes

    def vectorization_speedup(
        self, scalar_opcode: Opcode, element_bytes: int = 4
    ) -> float:
        """Estimate speedup from vectorizing a scalar operation.

        Compares scalar cost × N with vector cost + pack/unpack overhead,
        where N = simd_width/elem_size.
        Returns ratio > 1 if vectorization is beneficial.
        """
        lanes = self.simd_lanes(element_bytes)
        scalar_cost = self.latency(scalar_opcode) * lanes

        # Map scalar → vector opcode
        vec_map = {
            Opcode.Q_ADD: Opcode.Q_VADD,
            Opcode.Q_SUB: Opcode.Q_VSUB,
            Opcode.Q_MUL: Opcode.Q_VMUL,
            Opcode.Q_DIV: Opcode.Q_VDIV,
        }
        vec_opcode = vec_map.get(scalar_opcode)
        if vec_opcode is None:
            return 1.0  # not vectorizable

        vec_cost = self.latency(vec_opcode)
        if vec_cost == 0:
            return float(lanes)

        # Add pack/unpack overhead per vectorized group
        pack_overhead = self.pack_cost.pack_latency + self.pack_cost.unpack_latency
        total_vec_cost = vec_cost + pack_overhead

        return scalar_cost / total_vec_cost

    def should_vectorize(
        self, scalar_opcode: Opcode, trip_count: int,
        element_bytes: int = 4, overhead_cycles: int = 4,
    ) -> bool:
        """Decide if a loop/sequence should be vectorized.

        Factors: trip count, vector width, instruction cost,
        pack/unpack data marshalling cost, setup/cleanup overhead.
        Short sequences (< min_vectorize_count) stay scalar.
        """
        lanes = self.simd_lanes(element_bytes)
        # Minimum trip count must justify pack/unpack overhead
        min_trip = max(lanes * 2, self.min_vectorize_count)
        if trip_count < min_trip:
            return False  # too few iterations

        vec_map = {
            Opcode.Q_ADD: Opcode.Q_VADD, Opcode.Q_SUB: Opcode.Q_VSUB,
            Opcode.Q_MUL: Opcode.Q_VMUL, Opcode.Q_DIV: Opcode.Q_VDIV,
        }
        vec_opcode = vec_map.get(scalar_opcode, scalar_opcode)

        scalar_cost = self.latency(scalar_opcode) * trip_count

        # Vector cost = compute + pack/unpack overhead per group + setup
        vec_iterations = trip_count // lanes
        pack_per_group = self.pack_cost.pack_latency + self.pack_cost.unpack_latency
        vec_cost = (self.latency(vec_opcode) + pack_per_group) * vec_iterations + overhead_cycles

        # Remainder scalar cost
        remainder = trip_count % lanes
        vec_cost += self.latency(scalar_opcode) * remainder

        return vec_cost < scalar_cost

    # ── Summary/Debug ────────────────────────────────────────

    def summary(self) -> str:
        """Human-readable summary of the cost model."""
        lines = [
            f"CostModel: {self.arch} ({self.cpu})",
            f"  Issue width: {self.issue_width}",
            f"  SIMD width: {self.max_simd_width} bytes ({self.max_simd_width * 8}-bit)",
            f"  Branch miss penalty: {self.branch.miss_penalty:.0f} cycles",
            f"  Memory: L1={self.memory.l1_latency:.0f}c L2={self.memory.l2_latency:.0f}c"
            f" L3={self.memory.l3_latency:.0f}c RAM={self.memory.mem_latency:.0f}c",
            f"  Cache: L1D={self.cache.l1d_size_kb}KB/{self.cache.l1d_assoc}-way"
            f" L2={self.cache.l2_size_kb}KB/{self.cache.l2_assoc}-way"
            f" line={self.cache.cache_line_size}B",
            f"  TLB: dTLB={self.tlb.l1_dtlb_entries} iTLB={self.tlb.l1_itlb_entries}"
            f" L2TLB={self.tlb.l2_tlb_entries} page={self.tlb.page_size}B",
            f"  Prefetch: HW={self.prefetch.hw_prefetch_distance} lines"
            f" hint={self.prefetch.prefetch_hint_size}B",
            f"  Pack/Unpack: pack={self.pack_cost.pack_latency}c"
            f" unpack={self.pack_cost.unpack_latency}c"
            f" align_penalty={self.pack_cost.alignment_penalty:.1f}×"
            f" min_vec_count={self.min_vectorize_count}",
            f"  Spill cost: {self.spill.total} cycles (store={self.spill.spill_store} + load={self.spill.spill_load})",
            "",
            "  Opcode costs (latency / IPC):",
        ]
        for opcode in sorted(self._costs, key=lambda o: o.name):
            e = self._costs[opcode]
            lines.append(f"    {opcode.name:20s} → {e.mnemonic:8s}  lat={e.latency:2d}  thr={e.throughput:5.2f}")
        return "\n".join(lines)
