#!/usr/bin/env python3
"""Generate the focused Stage-1 bootstrap regression fixtures and manifest."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TEST_DIR = ROOT / "tests" / "bootstrap_codegen"
MANIFEST = TEST_DIR / "manifest.json"

BASELINE_EXPECTED = {
    "cg_alloc_byte.vri": "65\n",
    "cg_arith.vri": "30\n90\n",
    "cg_assign.vri": "42\n",
    "cg_call.vri": "42\n",
    "cg_call0.vri": "42\n",
    "cg_call_stmt.vri": "42\n",
    "cg_comment.vri": "42\n",
    "cg_getarg.vri": "2\n",
    "cg_if.vri": "1\n",
    "cg_if_else.vri": "7\n",
    "cg_let_call_arg.vri": "42\n",
    "cg_local_scope.vri": "7\n",
    "cg_mod2.vri": "42\n",
    "cg_mul.vri": "30\n90\n",
    "cg_multilocal.vri": "30\n",
    "cg_multiparam.vri": "42\n",
    "cg_nested_if.vri": "1\n",
    "cg_params_forms.vri": "42\n42\n",
    "cg_printstr.vri": "hi\n42\n",
    "cg_scale65_call.vri": "0\n7\n",
    "cg_scale65_print.vri": "42\n",
    "cg_scale65_trace.vri": "1\n2\n0\n3\n",
    "cg_scale70.vri": "10\n41\n",
    "cg_var.vri": "30\n",
    "cg_when.vri": "3\n",
    "cg_when_arena.vri": "50\n",
    "cg_when_assign.vri": "7\n",
}

CASES: dict[str, tuple[str, str]] = {}


def case(name: str, expected: str | int, body: str) -> None:
    if name in CASES:
        raise ValueError(f"duplicate generated test: {name}")
    source = f"# GENERATED by tools/generate_bootstrap_regressions.py\n# EXPECT: {expected}\n{body.strip()}\n"
    CASES[name] = (f"{expected}\n", source)


def main_program(expr: str) -> str:
    return f"""
func main:
    print({expr});
    out 0;
end.
"""


# Expression precedence and literal encoding (15).
for name, expected, expr in [
    ("cg_prec_01_mul_before_add.vri", 14, "2 + 3 * 4"),
    ("cg_prec_02_paren_before_mul.vri", 20, "(2 + 3) * 4"),
    ("cg_prec_03_mul_before_sub.vri", 8, "20 - 3 * 4"),
    ("cg_prec_04_paren_sub.vri", 68, "(20 - 3) * 4"),
    ("cg_prec_05_left_div.vri", 10, "100 / 5 / 2"),
    ("cg_prec_06_grouped_div.vri", 10, "100 / (5 * 2)"),
    ("cg_prec_07_shift_before_add.vri", 17, "1 + 2 shl 3"),
    ("cg_prec_08_grouped_add_shift.vri", 24, "(1 + 2) shl 3"),
    ("cg_prec_09_shift_then_add.vri", 17, "64 shr 2 + 1"),
    ("cg_prec_10_add_before_band.vri", 3, "7 bit_and 3 + 8"),
    ("cg_prec_11_band_before_bor.vri", 3, "1 bit_or 2 bit_and 3"),
    ("cg_prec_12_hex_literal.vri", 42, "0x2A"),
    ("cg_prec_13_large_immediate.vri", 70001, "70000 + 1"),
    ("cg_prec_14_nested_parens.vri", 42, "((((40 + 2))))"),
    ("cg_prec_15_mul_div_chain.vri", 36, "84 / 7 * 3"),
]:
    case(name, expected, main_program(expr))

# Nested, forward, and high-arity calls (10).
case("cg_call_nested_01.vri", 8, """
func inc(x): out x + 1; end.
func twice(x): out x * 2; end.
func main: print(twice(inc(3))); out 0; end.
""")
case("cg_call_nested_02.vri", 18, """
func add(a, b): out a + b; end.
func mul(a, b): out a * b; end.
func main: print(add(mul(3, 4), mul(2, 3))); out 0; end.
""")
case("cg_call_forward_01.vri", 42, """
func main: print(answer()); out 0; end.
func answer: out 42; end.
""")
case("cg_call_chain_01.vri", 9, """
func a(x): out b(x + 1); end.
func b(x): out c(x + 1); end.
func c(x): out d(x + 1); end.
func d(x): out x + 1; end.
func main: print(a(5)); out 0; end.
""")
case("cg_call_eight_args.vri", 36, """
func sum8(a, b, c, d, e, f, g, h):
    out a + b + c + d + e + f + g + h;
end.
func main: print(sum8(1, 2, 3, 4, 5, 6, 7, 8)); out 0; end.
""")
case("cg_call_expr_args.vri", 42, """
func add(a, b): out a + b; end.
func main: print(add(10 * 2, 11 * 2)); out 0; end.
""")
case("cg_call_reuse_result.vri", 42, """
func seven: out 7; end.
func main:
    let x = seven();
    print(x * seven() - 7);
    out 0;
end.
""")
case("cg_call_statement_02.vri", 42, """
func ignored(x): out x + 100; end.
func main: ignored(9); print(42); out 0; end.
""")
case("cg_call_block_params.vri", 42, """
func add:
    in(a, b)
    out a + b;
end.
func main: print(add(19, 23)); out 0; end.
""")
case("cg_call_paren_params.vri", 42, """
func add(a: int, b: int): out a + b; end.
func main: print(add(20, 22)); out 0; end.
""")

# Direct and mutual recursion (5).
case("cg_rec_factorial.vri", 120, """
func fact(n):
    if n <= 1 do out 1; end
    out n * fact(n - 1);
end.
func main: print(fact(5)); out 0; end.
""")
case("cg_rec_fibonacci.vri", 13, """
func fib(n):
    if n <= 1 do out n; end
    out fib(n - 1) + fib(n - 2);
end.
func main: print(fib(7)); out 0; end.
""")
case("cg_rec_sumdown.vri", 55, """
func sumdown(n):
    if n == 0 do out 0; end
    out n + sumdown(n - 1);
end.
func main: print(sumdown(10)); out 0; end.
""")
case("cg_rec_gcd_sub.vri", 6, """
func gcd(a, b):
    if a == b do out a; end
    if a > b do out gcd(a - b, b); end
    out gcd(a, b - a);
end.
func main: print(gcd(48, 18)); out 0; end.
""")
case("cg_rec_mutual_even.vri", 1, """
func is_even(n):
    if n == 0 do out 1; end
    out is_odd(n - 1);
end.
func is_odd(n):
    if n == 0 do out 0; end
    out is_even(n - 1);
end.
func main: print(is_even(10)); out 0; end.
""")

# Array-like memory behavior through the Stage-1 memory builtins (10).
case("cg_mem_byte_edges.vri", 131, """
func main:
    let p = alloc(16);
    write_byte(p, 0, 65);
    write_byte(p, 15, 66);
    print(read_byte(p, 0) + read_byte(p, 15));
    out 0;
end.
""")
case("cg_mem_byte_sum.vri", 10, """
func main:
    let p = alloc(4);
    write_byte(p, 0, 1);
    write_byte(p, 1, 2);
    write_byte(p, 2, 3);
    write_byte(p, 3, 4);
    print(read_byte(p, 0) + read_byte(p, 1) + read_byte(p, 2) + read_byte(p, 3));
    out 0;
end.
""")
case("cg_mem_word_roundtrip.vri", 70000, """
func main:
    let p = alloc(16);
    write_word(p, 0, 70000);
    print(read_word(p, 0));
    out 0;
end.
""")
case("cg_mem_word_offset.vri", 42, """
func main:
    let p = alloc(24);
    write_word(p, 8, 42);
    print(read_word(p, 8));
    out 0;
end.
""")
case("cg_mem_alloc_isolation.vri", 3, """
func main:
    let a = alloc(8);
    let b = alloc(8);
    write_byte(a, 0, 1);
    write_byte(b, 0, 2);
    print(read_byte(a, 0) + read_byte(b, 0));
    out 0;
end.
""")
case("cg_mem_alloc_zero.vri", 1, """
func main:
    let a = alloc(0);
    let b = alloc(8);
    if a == b do print(1); else print(0); end
    out 0;
end.
""")
case("cg_mem_loop_pattern.vri", 45, """
func main:
    let p = alloc(10);
    let i = 0;
    when i < 10 loop
        write_byte(p, i, i);
        i = i + 1;
    end
    let sum = 0;
    i = 0;
    when i < 10 loop
        sum = sum + read_byte(p, i);
        i = i + 1;
    end
    print(sum);
    out 0;
end.
""")
case("cg_mem_byte_overwrite.vri", 42, """
func main:
    let p = alloc(1);
    write_byte(p, 0, 7);
    write_byte(p, 0, 42);
    print(read_byte(p, 0));
    out 0;
end.
""")
case("cg_mem_dynamic_offset.vri", 65, """
func main:
    let p = alloc(8);
    let i = 3;
    write_byte(p, i, 65);
    print(read_byte(p, i));
    out 0;
end.
""")
case("cg_mem_word_overwrite.vri", 99, """
func main:
    let p = alloc(8);
    write_word(p, 0, 42);
    write_word(p, 0, 99);
    print(read_word(p, 0));
    out 0;
end.
""")

# String literal emission boundaries (5).
for name, expected, literal in [
    ("cg_str_empty.vri", 42, ""),
    ("cg_str_one.vri", 42, "x"),
    ("cg_str_fifteen.vri", 42, "123456789012345"),
    ("cg_str_digits.vri", 42, "0123456789"),
    ("cg_str_spaces.vri", 42, "a b c"),
]:
    case(name, f"{literal}\\n42", f"""
func main:
    print "{literal}";
    print 42;
    out 0;
end.
""")

# Six if comparisons, six else paths, and six terminating loops (18).
for index, (op, left, right) in enumerate([
    ("==", 4, 4), ("!=", 4, 5), ("<", 4, 5),
    ("<=", 5, 5), (">", 6, 5), (">=", 5, 5),
], 1):
    case(f"cg_ctrl_if_{index:02d}.vri", index, f"""
func main:
    if {left} {op} {right} do print({index}); else print(0); end
    out 0;
end.
""")
for index, (op, left, right) in enumerate([
    ("==", 4, 5), ("!=", 4, 4), ("<", 5, 4),
    ("<=", 6, 5), (">", 5, 6), (">=", 4, 5),
], 1):
    case(f"cg_ctrl_else_{index:02d}.vri", index + 10, f"""
func main:
    if {left} {op} {right} do print(0); else print({index + 10}); end
    out 0;
end.
""")
loop_cases = [
    ("cg_ctrl_when_eq.vri", 1, "let i = 0;", "i == 0", "i = 1"),
    ("cg_ctrl_when_ne.vri", 3, "let i = 0;", "i != 3", "i = i + 1"),
    ("cg_ctrl_when_lt.vri", 4, "let i = 0;", "i < 4", "i = i + 1"),
    ("cg_ctrl_when_le.vri", 4, "let i = 0;", "i <= 3", "i = i + 1"),
    ("cg_ctrl_when_gt.vri", 0, "let i = 4;", "i > 0", "i = i - 1"),
    ("cg_ctrl_when_ge.vri", 0, "let i = 4;", "i >= 1", "i = i - 1"),
]
for name, expected, init, condition, update in loop_cases:
    case(name, expected, f"""
func main:
    {init}
    when {condition} loop {update}; end
    print(i);
    out 0;
end.
""")

# Locals, assignment, and parameter preservation (5).
case("cg_local_many.vri", 36, """
func main:
    let a = 1; let b = 2; let c = 3; let d = 4;
    let e = 5; let f = 6; let g = 7; let h = 8;
    print(a + b + c + d + e + f + g + h);
    out 0;
end.
""")
case("cg_local_assign_chain.vri", 42, """
func main:
    let a = 1; let b = 2;
    a = b; b = 40; a = a + b;
    print(a); out 0;
end.
""")
case("cg_local_loop_accum.vri", 55, """
func main:
    let i = 1; let sum = 0;
    when i <= 10 loop sum = sum + i; i = i + 1; end
    print(sum); out 0;
end.
""")
case("cg_param_preserve_nested.vri", 42, """
func identity(x): out x; end.
func add(a, b): out identity(a) + identity(b); end.
func main: print(add(19, 23)); out 0; end.
""")
case("cg_param_assign.vri", 42, """
func bump(x): x = x + 1; out x; end.
func main: print(bump(41)); out 0; end.
""")

# Native i64 wrapping and parser edge cases (5).
case("cg_edge_wrap_add.vri", 0, main_program("(1 shl 63) + (1 shl 63)"))
case(
    "cg_edge_wrap_mul.vri",
    0,
    main_program("(65536 * 65536) * (65536 * 65536)"),
)
case("cg_edge_minus_one.vri", -1, main_program("0 - 1"))
case("cg_edge_div_negative.vri", -7, main_program("(0 - 42) / 6"))
case("cg_edge_comment_eof.vri", 42, """
func main:
    print(42);
    out 0;
end.
# trailing comment without code
""")


def generate() -> None:
    TEST_DIR.mkdir(parents=True, exist_ok=True)
    obsolete = TEST_DIR / "cg_global.vri"
    if obsolete.exists():
        obsolete.unlink()

    local_scope = TEST_DIR / "cg_local_scope.vri"
    local_scope.write_text(
        "# Globals are not in the Stage-1 subset; verify local reassignment instead.\n"
        "# EXPECT: 7\n"
        "func main:\n"
        "    let x = 0;\n"
        "    x = 7;\n"
        "    print(x);\n"
        "    out 0;\n"
        "end.\n",
        encoding="utf-8",
    )

    for name, (_, source) in sorted(CASES.items()):
        (TEST_DIR / name).write_text(source, encoding="utf-8")

    expected = dict(BASELINE_EXPECTED)
    expected.update({name: stdout.replace("\\n", "\n") for name, (stdout, _) in CASES.items()})
    if len(expected) != 100:
        raise AssertionError(f"expected exactly 100 tests, got {len(expected)}")
    missing = sorted(name for name in expected if not (TEST_DIR / name).is_file())
    if missing:
        raise FileNotFoundError(f"missing baseline tests: {missing}")

    manifest = {
        "schema": 1,
        "notes": {
            "supported": [
                "expression precedence",
                "recursion",
                "nested calls",
                "array-like memory via alloc/read/write",
                "string literals",
                "control flow",
                "i64 overflow",
                "parser and runtime edge cases",
            ],
            "unsupported_in_stage1": ["closures", "structs", "module globals"],
        },
        "tests": [
            {"file": name, "stdout": stdout, "exit": 0}
            for name, stdout in sorted(expected.items())
        ],
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"generated {len(CASES)} fixtures; manifest contains {len(expected)} tests")


if __name__ == "__main__":
    generate()
